import { Code, FileText, Paintbrush, Stethoscope, Leaf, Shield } from "lucide-react"

export const challengesData = [
  {
    id: 1,
    title: "Build a DEX Order Book on Cardano",
    description:
      "Create a decentralized exchange order book using Plutus smart contracts. Implement limit orders and market orders.",
    longDescription:
      "In this challenge, you'll build a decentralized exchange (DEX) order book on the Cardano blockchain using Plutus smart contracts. The order book should support limit orders and market orders, allowing users to trade ADA and native tokens. Your implementation should be efficient, secure, and follow best practices for Cardano smart contract development.",
    category: "Development",
    difficulty: "Intermediate",
    reward: "250",
    duration: "4 weeks",
    deadline: "2023-06-30",
    submissionCount: 24,
    createdBy: "SkillMint Team",
    createdAt: "2023-04-10",
    requirements: [
      "Implement a Plutus smart contract for the order book",
      "Support limit orders (buy and sell at specific prices)",
      "Support market orders (buy and sell at best available price)",
      "Include order matching logic",
      "Implement fee mechanism (0.3% of trade value)",
      "Write comprehensive documentation",
      "Include test cases",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Alice Johnson",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "May 15, 2023",
      },
      {
        id: 2,
        user: {
          name: "Bob Smith",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "May 18, 2023",
      },
      {
        id: 3,
        user: {
          name: "Charlie Brown",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Rejected",
        submittedAt: "May 20, 2023",
      },
    ],
    icon: <Code className="h-5 w-5" />,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-100 dark:bg-blue-900/30",
  },
  {
    id: 2,
    title: "Design a DeFi Dashboard UI",
    description:
      "Create a modern, user-friendly dashboard UI for a DeFi application. Focus on data visualization and accessibility.",
    longDescription:
      "In this design challenge, you'll create a comprehensive dashboard UI for a decentralized finance (DeFi) application. The dashboard should provide users with a clear overview of their assets, investments, and market data. Your design should prioritize usability, accessibility, and effective data visualization to help users make informed decisions.",
    category: "Design",
    difficulty: "Beginner",
    reward: "150",
    duration: "2 weeks",
    deadline: "2023-05-30",
    submissionCount: 42,
    createdBy: "SkillMint Team",
    createdAt: "2023-03-15",
    requirements: [
      "Create a responsive dashboard design (mobile and desktop)",
      "Include portfolio overview with asset allocation",
      "Design charts for historical performance",
      "Include market data section with key metrics",
      "Design transaction history view",
      "Ensure accessibility compliance (WCAG 2.1 AA)",
      "Provide design system components",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Diana Prince",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "April 10, 2023",
      },
      {
        id: 2,
        user: {
          name: "Ethan Hunt",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "April 12, 2023",
      },
      {
        id: 3,
        user: {
          name: "Fiona Gallagher",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "April 15, 2023",
      },
    ],
    icon: <Paintbrush className="h-5 w-5" />,
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-100 dark:bg-teal-900/30",
  },
  {
    id: 3,
    title: "Write a Technical Guide on NFT Minting",
    description:
      "Create a comprehensive guide explaining the technical process of minting NFTs on the Cardano blockchain.",
    longDescription:
      "In this content challenge, you'll write a detailed technical guide explaining the process of minting NFTs on the Cardano blockchain. The guide should be accessible to developers with basic blockchain knowledge but should cover advanced concepts as well. Your guide should include code examples, best practices, and explanations of the underlying technology.",
    category: "Content",
    difficulty: "Beginner",
    reward: "100",
    duration: "2 weeks",
    deadline: "2023-04-30",
    submissionCount: 18,
    createdBy: "SkillMint Team",
    createdAt: "2023-02-20",
    requirements: [
      "Explain the Cardano NFT standard (CIP-25)",
      "Cover the technical process of minting NFTs",
      "Include code examples in Plutus",
      "Explain metadata structure and standards",
      "Cover best practices for NFT projects",
      "Include section on NFT marketplaces on Cardano",
      "Provide resources for further learning",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "George Miller",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "March 5, 2023",
      },
      {
        id: 2,
        user: {
          name: "Hannah Baker",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Rejected",
        submittedAt: "March 8, 2023",
      },
    ],
    icon: <FileText className="h-5 w-5" />,
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-100 dark:bg-green-900/30",
  },
  {
    id: 4,
    title: "Implement a Cardano Wallet Connector",
    description: "Build a React component that connects to popular Cardano wallets like Nami, Eternl, and Flint.",
    longDescription:
      "In this development challenge, you'll create a reusable React component that allows users to connect their Cardano wallets to a web application. The component should support multiple popular Cardano wallets including Nami, Eternl, Flint, and others. Your implementation should handle wallet detection, connection, and basic transaction functionality.",
    category: "Development",
    difficulty: "Intermediate",
    reward: "200",
    duration: "3 weeks",
    deadline: "2023-05-15",
    submissionCount: 15,
    createdBy: "SkillMint Team",
    createdAt: "2023-03-01",
    requirements: [
      "Create a React component for wallet connection",
      "Support multiple Cardano wallets (Nami, Eternl, Flint, etc.)",
      "Implement wallet detection and connection",
      "Add functionality to get wallet balance",
      "Implement basic transaction sending",
      "Include comprehensive documentation",
      "Write unit tests for the component",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Ian Malcolm",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "April 20, 2023",
      },
    ],
    icon: <Code className="h-5 w-5" />,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-100 dark:bg-blue-900/30",
  },
  {
    id: 5,
    title: "Create an Educational Infographic on Cardano",
    description:
      "Design an informative and visually appealing infographic explaining Cardano's Ouroboros consensus mechanism.",
    longDescription:
      "In this design challenge, you'll create an educational infographic that explains Cardano's Ouroboros consensus mechanism in a visually engaging way. The infographic should break down complex technical concepts into digestible visual elements that help newcomers understand how Cardano's proof-of-stake system works. Your design should be both informative and visually appealing.",
    category: "Design",
    difficulty: "Beginner",
    reward: "120",
    duration: "1 week",
    deadline: "2023-04-15",
    submissionCount: 31,
    createdBy: "SkillMint Team",
    createdAt: "2023-02-10",
    requirements: [
      "Create a visually appealing infographic design",
      "Explain Ouroboros consensus in simple terms",
      "Include visual representations of key concepts",
      "Compare with other consensus mechanisms",
      "Design for both digital sharing and printing",
      "Include accurate technical information",
      "Provide source files in standard design formats",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Julia Roberts",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "March 15, 2023",
      },
      {
        id: 2,
        user: {
          name: "Kevin Hart",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "March 18, 2023",
      },
    ],
    icon: <Paintbrush className="h-5 w-5" />,
    color: "text-teal-600 dark:text-teal-400",
    bgColor: "bg-teal-100 dark:bg-teal-900/30",
  },
  {
    id: 6,
    title: "Develop a Smart Contract for NFT Royalties",
    description: "Create a Plutus smart contract that implements royalty payments for NFT secondary sales.",
    longDescription:
      "In this advanced development challenge, you'll create a Plutus smart contract that implements royalty payments for NFT secondary sales on the Cardano blockchain. The smart contract should automatically distribute a percentage of each secondary sale to the original creator while handling the remainder of the payment to the seller. Your implementation should be secure, efficient, and follow best practices for Cardano smart contract development.",
    category: "Development",
    difficulty: "Advanced",
    reward: "350",
    duration: "6 weeks",
    deadline: "2023-06-15",
    submissionCount: 8,
    createdBy: "SkillMint Team",
    createdAt: "2023-04-01",
    requirements: [
      "Implement a Plutus smart contract for NFT royalties",
      "Support configurable royalty percentages",
      "Ensure secure payment distribution",
      "Handle edge cases and error conditions",
      "Optimize for efficiency and low fees",
      "Write comprehensive documentation",
      "Include test cases and examples",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Liam Nelson",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "May 10, 2023",
      },
    ],
    icon: <Code className="h-5 w-5" />,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-100 dark:bg-blue-900/30",
  },
  // New Healthcare Challenge
  {
    id: 7,
    title: "Develop a Blockchain-Based Medical Records System",
    description:
      "Create a secure, privacy-focused medical records system using blockchain technology for data integrity and patient control.",
    longDescription:
      "In this healthcare challenge, you'll develop a prototype for a blockchain-based medical records system that ensures data integrity while giving patients control over their health information. The system should allow secure sharing of medical records between healthcare providers with patient consent, maintain an immutable audit trail, and protect sensitive health data through encryption and access controls.",
    category: "Healthcare",
    difficulty: "Advanced",
    reward: "400",
    duration: "8 weeks",
    deadline: "2023-07-30",
    submissionCount: 5,
    createdBy: "SkillMint Team",
    createdAt: "2023-04-15",
    requirements: [
      "Design a blockchain architecture for storing medical record access permissions",
      "Implement secure patient authentication and authorization",
      "Create a consent management system for data sharing",
      "Develop an audit trail for all record access",
      "Ensure HIPAA compliance in the system design",
      "Implement encryption for sensitive health data",
      "Create a user-friendly interface for patients and providers",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Maria Chen",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "May 20, 2023",
      },
    ],
    icon: <Stethoscope className="h-5 w-5" />,
    color: "text-red-600 dark:text-red-400",
    bgColor: "bg-red-100 dark:bg-red-900/30",
  },
  // New Agriculture Challenge
  {
    id: 8,
    title: "Build a Supply Chain Tracking System for Organic Produce",
    description:
      "Develop a blockchain solution to track organic produce from farm to consumer, ensuring authenticity and transparency.",
    longDescription:
      "In this agriculture challenge, you'll create a blockchain-based supply chain tracking system for organic produce. The system should track products from farm to consumer, verifying organic certification, farming practices, and handling throughout the supply chain. Your solution should provide consumers with transparent information about the products they purchase while helping farmers prove the authenticity of their organic practices.",
    category: "Agriculture",
    difficulty: "Intermediate",
    reward: "300",
    duration: "5 weeks",
    deadline: "2023-06-30",
    submissionCount: 12,
    createdBy: "SkillMint Team",
    createdAt: "2023-03-25",
    requirements: [
      "Design a blockchain architecture for supply chain tracking",
      "Implement QR code or NFC-based product identification",
      "Create a verification system for organic certification",
      "Develop interfaces for farmers, distributors, retailers, and consumers",
      "Include environmental impact metrics in the tracking data",
      "Implement a mobile app for consumer verification",
      "Ensure the system is usable in areas with limited connectivity",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Thomas Green",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Approved",
        submittedAt: "April 28, 2023",
      },
    ],
    icon: <Leaf className="h-5 w-5" />,
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-100 dark:bg-green-900/30",
  },
  // New Security Challenge
  {
    id: 9,
    title: "Develop a Decentralized Identity Verification System",
    description:
      "Create a secure, privacy-preserving identity verification system using zero-knowledge proofs and blockchain technology.",
    longDescription:
      "In this security challenge, you'll develop a decentralized identity verification system that allows users to prove their identity without revealing sensitive personal information. Using zero-knowledge proofs and blockchain technology, your system should enable selective disclosure of identity attributes while maintaining user privacy and security. The solution should be resistant to common identity theft attacks while remaining user-friendly.",
    category: "Security",
    difficulty: "Advanced",
    reward: "450",
    duration: "7 weeks",
    deadline: "2023-07-15",
    submissionCount: 7,
    createdBy: "SkillMint Team",
    createdAt: "2023-04-05",
    requirements: [
      "Implement zero-knowledge proof protocols for identity verification",
      "Create a decentralized identity wallet for users",
      "Develop a system for issuing and verifying credentials",
      "Implement selective disclosure of identity attributes",
      "Ensure compliance with relevant privacy regulations",
      "Create a user-friendly interface for managing identity",
      "Include comprehensive security documentation and threat model",
    ],
    submissions: [
      {
        id: 1,
        user: {
          name: "Sophia Rodriguez",
          avatar: "/placeholder.svg?height=40&width=40",
        },
        status: "Pending",
        submittedAt: "May 12, 2023",
      },
    ],
    icon: <Shield className="h-5 w-5" />,
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-100 dark:bg-purple-900/30",
  },
]
